### ISSUE TITLE
가상 서버 지원 신청해보기?

### ISSUE THREAD

**Issue by mozodev** [peace-code/peace-code.github.io#1]
블로그 새로 작성하느라 저장소를 지우고 포크해서 새로 만들었는데

전에 썼던 회의록이 다 날아갔네요~  미쳤나봐요 ㅜㅜ 죄송합니다. 

위키 백업도 안해놓고 부주의하게 저장소를 날려버렸네요.
## [NIPA 『 커뮤니티 소모임 활동 및 행사 지원 』](http://www.oss.kr/oss_business7_1)

http://www.oss.kr/oss_business7_1
밑에서 3번째 가상개발환경 지원 - 4월부터 신청이라고 하네요...
## [네이버 개발자 센터 커뮤니티 지원](http://developer.naver.com/wiki/pages/community)

http://developer.naver.com/wiki/pages/community
음 신청서 이런 건 안보이고 밑에 메일주소가 있네요..
기타 문의 : D2 Program 공통메일, d2@navercorp.com
## [다음 개발자 센터 커뮤니티 지원](http://dna.daum.net/share/community)

http://dna.daum.net/share/community

```
파이썬 마을
국내 파이썬(Python) 사용자들의 대표 커뮤니티입니다.Daum DNA에서 가상 서버를 제공하고 있습니다.
```

음 이런 문구가 보이네요~

**Comment by wagurano** [comment]
세계 평화를 위해 새로 시작하는 기분으로 하죠^^
슬랙에 회의록은 하나는 있는데 다른 것도 있는지 모르겠어요.

2015년 2월 9일 오전 10:55, Yeongtaek Hong notifications@github.com님이 작성:

**Comment by rest515** [comment]
ㅎㅎ 저도 한번 날려본 적이 있어서.. 뭐. ㅎ

이번주에 작업 좀 진행하고 공유할께요. :)

_PEACE !!!_

2015-02-09 13:07 GMT+09:00 Seongjun Peter Kim notifications@github.com:

**Comment by mozodev** [comment]
아 그렇군요~ 하나라도 있어서 다행이네요. 가져와서 추가했어요~

**Comment by mozodev** [comment]
이제 우주 서버를 운영 중이므로 필요없어서 닫습니다. ㅋㅋ
