### ISSUE TITLE
slack 관련

### ISSUE THREAD

**Issue by mozodev** [peace-code/peace-code.github.io#2]
peacecode로 새로 만들고 채널에서 프로젝트 별로 이야기하는게 좋지 않을까요?

그리고 코드포서울에도 적용해봤는데
- http://slack.codeforseoul.org (슬랙 자동 초대: https://github.com/rauchg/slackin)
- 깃헙이 만든 IRC봇 https://github.com/github/hubot 

요런거 올려보면 어떨까요? ㅎㅎ

**Comment by wagurano** [comment]
전에 api가 막혔다고 하던데 제한이 풀렸나보네요.

**Comment by mozodev** [comment]
ㅇㅇ 보시다 시피 잘되요~ ㅎㅎ

**Comment by mozodev** [comment]
http://slackin.peacecode.org online! 닫습니다~
